# Generated by Django 4.2.7 on 2023-12-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goodsvisitcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsVisitCount',
        ),
    ]
