# Generated by Django 4.2.6 on 2023-10-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True, verbose_name='项目名称')),
                ('project_type', models.CharField(max_length=10, unique=True, verbose_name='项目类型')),
                ('project_description', models.CharField(max_length=255, unique=True, verbose_name='项目描述')),
                ('project_status', models.BooleanField(default=False, verbose_name='项目状态')),
            ],
            options={
                'verbose_name': '项目信息表',
                'verbose_name_plural': '项目信息表',
                'db_table': 'project_info',
            },
        ),
    ]
