# Generated by Django 4.2.6 on 2023-10-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfomation',
            name='project_description',
            field=models.CharField(max_length=255, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='projectinfomation',
            name='project_type',
            field=models.CharField(max_length=10, verbose_name='项目类型'),
        ),
    ]
