# Generated by Django 4.2.7 on 2023-11-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectinfomation',
            table='tb_project_info',
        ),
    ]
